### Import ids for randomization

In [1]:
import pandas as pd

pos_id = pd.read_csv("pos_cluster/positive_representative_data.tsv" , sep="\t")
neg_id = pd.read_csv("neg_cluster/negative_representative_data.tsv" , sep="\t")
pos_id['Class']="Positive"
neg_id['Class']="Negative"
pos_id.head()

  EntryID  OrganismName  Kingdom  SequenceLength  SPStart  SPEnd     Class
0  O43155  Homo sapiens  Metazoa             660        1     35  Positive
1  O43866  Homo sapiens  Metazoa             347        1     19  Positive
2  O75629  Homo sapiens  Metazoa             220        1     31  Positive
3  O94985  Homo sapiens  Metazoa             981        1     28  Positive
4  P01579  Homo sapiens  Metazoa             166        1     23  Positive

### Randomization of positive and negative ids

In [2]:
#DO NOT RERUN THIS CELL

pos_random = pos_id.sample(frac=1).reset_index(drop=True)
neg_random = neg_id.sample(frac=1).reset_index(drop=True)

In [3]:
pos_random.head()

,EntryID,OrganismName,Kingdom,SequenceLength,SPStart,SPEnd,Class
0,P0C8G7,Pomacea canaliculata,Metazoa,286,1,30,Positive
1,P48816,Bombyx mori,Metazoa,137,1,18,Positive
2,Q42502,Solanum tuberosum,Viridiplantae,386,1,23,Positive
3,P11590,Mus musculus,Metazoa,178,1,16,Positive
4,Q6DWK3,Colletotrichum lindemuthianum,Fungi,248,1,26,Positive

In [4]:
neg_random.head()

,EntryID,OrganismName,Kingdom,SequenceLength,HelixDomain,Class
0,P32336,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,851,False,Negative
1,P36088,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,180,False,Negative
2,P54939,Gallus gallus,Metazoa,2541,False,Negative
3,Q96BN2,Homo sapiens,Metazoa,335,False,Negative
4,P87231,Schizosaccharomyces pombe (strain 972 / ATCC 2...,Fungi,608,False,Negative

### Divide 80% training and 20% benchmark sets

In [5]:
#training set creation

n_pos = int(len(pos_random) * 0.8)
n_neg = int(len(neg_random) * 0.8)

training_pos = pos_random[:n_pos] 
training_neg = neg_random[:n_neg]

In [6]:
print(n_pos , n_neg)

874 7147

In [7]:
training_pos

,EntryID,OrganismName,Kingdom,SequenceLength,SPStart,SPEnd,Class
0,P0C8G7,Pomacea canaliculata,Metazoa,286,1,30,Positive
1,P48816,Bombyx mori,Metazoa,137,1,18,Positive
2,Q42502,Solanum tuberosum,Viridiplantae,386,1,23,Positive
3,P11590,Mus musculus,Metazoa,178,1,16,Positive
4,Q6DWK3,Colletotrichum lindemuthianum,Fungi,248,1,26,Positive
...,...,...,...,...,...,...,...
869,P19438,Homo sapiens,Metazoa,455,1,29,Positive
870,P07359,Homo sapiens,Metazoa,652,1,16,Positive
871,Q01129,Rattus norvegicus,Metazoa,354,1,16,Positive
872,P25404,Mirabilis jalapa,Viridiplantae,63,1,27,Positive
873,P48747,Oryctolagus cuniculus,Metazoa,557,1,21,Positive

In [8]:
training_neg

,EntryID,OrganismName,Kingdom,SequenceLength,HelixDomain,Class
0,P32336,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,851,False,Negative
1,P36088,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,180,False,Negative
2,P54939,Gallus gallus,Metazoa,2541,False,Negative
3,Q96BN2,Homo sapiens,Metazoa,335,False,Negative
4,P87231,Schizosaccharomyces pombe (strain 972 / ATCC 2...,Fungi,608,False,Negative
...,...,...,...,...,...,...
7142,X5HYT8,Oryza sativa subsp. japonica,Viridiplantae,425,False,Negative
7143,P97411,Mus musculus,Metazoa,478,False,Negative
7144,Q9P305,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,131,False,Negative
7145,P39995,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,279,False,Negative
7146,B6VQ60,Caenorhabditis elegans,Metazoa,612,False,Negative

In [9]:
#benchmark set creation

benchmark_pos = pos_random[n_pos:] 
benchmark_neg = neg_random[n_neg:]

In [10]:
benchmark_pos

,EntryID,OrganismName,Kingdom,SequenceLength,SPStart,SPEnd,Class
874,Q96DU3,Homo sapiens,Metazoa,332,1,21,Positive
875,P01588,Homo sapiens,Metazoa,193,1,27,Positive
876,P45478,Bos taurus,Metazoa,306,1,27,Positive
877,A1X159,Perna viridis,Metazoa,431,1,20,Positive
878,P01165,Sus scrofa,Metazoa,207,1,22,Positive
...,...,...,...,...,...,...,...
1088,O13547,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,238,1,22,Positive
1089,P31723,Penicillium citrinum,Fungi,511,1,35,Positive
1090,Q9NSA1,Homo sapiens,Metazoa,209,1,28,Positive
1091,Q8J0D2,Geotrichum sp. (strain M128),Fungi,812,1,23,Positive
1092,B0JFB8,Antheraea mylitta,Metazoa,105,1,19,Positive

In [11]:
benchmark_neg

,EntryID,OrganismName,Kingdom,SequenceLength,HelixDomain,Class
7147,P25038,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,676,False,Negative
7148,H2QII6,Pan troglodytes,Metazoa,3224,False,Negative
7149,F4I9G2,Arabidopsis thaliana,Viridiplantae,426,False,Negative
7150,Q9NW15,Homo sapiens,Metazoa,660,False,Negative
7151,Q6ZT62,Homo sapiens,Metazoa,677,False,Negative
...,...,...,...,...,...,...
8929,Q8VYM2,Arabidopsis thaliana,Viridiplantae,524,True,Negative
8930,Q8TD31,Homo sapiens,Metazoa,782,False,Negative
8931,Q9U405,Drosophila melanogaster,Metazoa,570,False,Negative
8932,Q06162,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,153,False,Negative
8933,Q5JNS0,Oryza sativa subsp. japonica,Viridiplantae,379,False,Negative

In [12]:
# Check if we have intersection between datasets

check1 = pd.merge(benchmark_neg , training_neg , how="inner")
check2 = pd.merge(benchmark_pos , training_pos , how="inner")
print(check1)
print(check2)

Empty DataFrame
Columns: [EntryID, OrganismName, Kingdom, SequenceLength, HelixDomain, Class]
Index: []
Empty DataFrame
Columns: [EntryID, OrganismName, Kingdom, SequenceLength, SPStart, SPEnd, Class]
Index: []

In [13]:
# Merge positive and negative benchmark sets

benchmark = pd.concat([benchmark_neg , benchmark_pos] , ignore_index=True)
#len(benchmark)
print(len(benchmark_pos),'+',len(benchmark_neg),'=',len(benchmark_neg)+len(benchmark_pos))

219 + 1787 = 2006

In [14]:
benchmark

,EntryID,OrganismName,Kingdom,SequenceLength,HelixDomain,Class,SPStart,SPEnd
0,P25038,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,676,False,Negative,NaN,NaN
1,H2QII6,Pan troglodytes,Metazoa,3224,False,Negative,NaN,NaN
2,F4I9G2,Arabidopsis thaliana,Viridiplantae,426,False,Negative,NaN,NaN
3,Q9NW15,Homo sapiens,Metazoa,660,False,Negative,NaN,NaN
4,Q6ZT62,Homo sapiens,Metazoa,677,False,Negative,NaN,NaN
...,...,...,...,...,...,...,...,...
2001,O13547,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,238,NaN,Positive,1.0,22.0
2002,P31723,Penicillium citrinum,Fungi,511,NaN,Positive,1.0,35.0
2003,Q9NSA1,Homo sapiens,Metazoa,209,NaN,Positive,1.0,28.0
2004,Q8J0D2,Geotrichum sp. (strain M128),Fungi,812,NaN,Positive,1.0,23.0
2005,B0JFB8,Antheraea mylitta,Metazoa,105,NaN,Positive,1.0,19.0

### Adding sequences for benchmark set from the fasta file

In [15]:
from Bio import SeqIO
import subprocess
import shlex
'''
Takes as input a list of ids 
and  a dataset of fasta sequences (for example the entire swissprot)
'''

#merge all the negative and positive representative sequences fasta files 
command = "cat neg_cluster/neg_rep_seq.fasta pos_cluster/pos_rep_seq.fasta" 
with open("rep_dataset.fasta", "w") as f:
    subprocess.run(shlex.split(command), stdout=f)
    
benchmark['Set']="Benchmark"
rep_dataset='rep_dataset.fasta'    
ids_to_get=benchmark['EntryID'].tolist() #convert the ids of the benchmark  to a list

found = 0 #keeps track of single ids.
counter = len(ids_to_get) #number of the ids inside the benchmark list


#find all the sequences inside the all representative sequences fasta file that corresponds to the ids inside the benchmark set
with open(rep_dataset , 'r') as file1:
    for prot in SeqIO.parse(file1 , 'fasta'):
        if str(prot.id) in ids_to_get:
            found = found + 1
            benchmark.loc[benchmark['EntryID'] == str(prot.id), 'Sequence'] = str(prot.seq)
        else:
            pass
            
print("how many ids are in the benchmark set: ", counter)
print("total number of sequences recovered: ",found)

how many ids are in the benchmark set:  2006
total number of sequences recovered:  2006

In [16]:
benchmark

,EntryID,OrganismName,Kingdom,SequenceLength,HelixDomain,Class,SPStart,SPEnd,Set,Sequence
0,P25038,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,676,False,Negative,NaN,NaN,Benchmark,MLRRHGLFWLKTCPRLNVLLNQSIPIPHLLHSRDICQQRWYAKGKR...
1,H2QII6,Pan troglodytes,Metazoa,3224,False,Negative,NaN,NaN,Benchmark,MRRSKADVERYIASVQGSTPSPRQKSIKGFYFAKLYYEAKEYDLAK...
2,F4I9G2,Arabidopsis thaliana,Viridiplantae,426,False,Negative,NaN,NaN,Benchmark,MSEMAASSAISLLDIKLRRFGVGASNHELRLTKWFKGDQAGAPTRR...
3,Q9NW15,Homo sapiens,Metazoa,660,False,Negative,NaN,NaN,Benchmark,MKVTLSALDTSESSFTPLVVIELAQDVKEETKEWLKNRIIAKKKDG...
4,Q6ZT62,Homo sapiens,Metazoa,677,False,Negative,NaN,NaN,Benchmark,MDRGLPGPATPAVTPQPPARPQDDEEAAAPHAAAGPDGQLGTVEQR...
...,...,...,...,...,...,...,...,...,...,...
2001,O13547,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,238,NaN,Positive,1.0,22.0,Benchmark,MRATTLLSSVVSLALLSKEVLATPPACLLACVAQVGKSSSTCDSLN...
2002,P31723,Penicillium citrinum,Fungi,511,NaN,Positive,1.0,35.0,Benchmark,MRLPVSFPLTVLSLLGSTIAHPYGETEAVLRSEPKSNQAKADAVKE...
2003,Q9NSA1,Homo sapiens,Metazoa,209,NaN,Positive,1.0,28.0,Benchmark,MDSDETGFEHSGLWVSVLAGLLLGACQAHPIPDSSPLLQFGGQVRQ...
2004,Q8J0D2,Geotrichum sp. (strain M128),Fungi,812,NaN,Positive,1.0,23.0,Benchmark,MVAVTSLGKALTALSILASLAVAKEHYEFKNVAIGGGGYITGIVAH...
2005,B0JFB8,Antheraea mylitta,Metazoa,105,NaN,Positive,1.0,19.0,Benchmark,MKAVITLLFLACILVVTYGDLICGTNYCKDHPCTSPIARASCRSPA...

### Adding sequences for training subset set from the fasta file

In [17]:
start=0
step_pos=n_pos//5
for i in range(1,6):
    if i==5:
        subset = pd.concat([subset , training_pos[start:]] , ignore_index=True)
        ids_to_get=training_pos[start:]['EntryID'].tolist()
    elif i==1:
        stop=i*step_pos
        subset=training_pos[start:stop]
        ids_to_get=training_pos[start:stop]['EntryID'].tolist()
        start=i*step_pos
    else:
        stop=i*step_pos
        subset = pd.concat([subset , training_pos[start:stop]] , ignore_index=True)
        ids_to_get=training_pos[start:stop]['EntryID'].tolist()
        start=i*step_pos
    print(f"Total number positive sequences in the subset {i}: ",len(subset))
    with open(rep_dataset , 'r') as file1:
        for prot in SeqIO.parse(file1 , 'fasta'):
            if str(prot.id) in ids_to_get:
                found = found + 1
                subset.loc[subset['EntryID'] == str(prot.id), 'Sequence'] = str(prot.seq)
                subset.loc[subset['EntryID'] == str(prot.id), 'Set'] = f"{i}"
            else:
                pass

###now work on negatives
step_neg=n_neg//5
start=0
for i in range(1,6):
    if i==5:
        subset = pd.concat([subset , training_neg[start:]], ignore_index=True)
        ids_to_get=training_neg[start:]['EntryID'].tolist()
    else:
        stop=i*step_neg
        subset = pd.concat([subset , training_neg[start:stop]] , ignore_index=True)
        ids_to_get=training_neg[start:stop]['EntryID'].tolist()
        start=i*step_neg
    print(f"Total number negative sequences in the subset {i}: ",len(subset))
    with open(rep_dataset , 'r') as file1:
        for prot in SeqIO.parse(file1 , 'fasta'):
            if str(prot.id) in ids_to_get:
                    found = found + 1
                    subset.loc[subset['EntryID'] == str(prot.id), 'Sequence'] = str(prot.seq)
                    subset.loc[subset['EntryID'] == str(prot.id), 'Set'] = f"{i}"
            else:
                pass

Total number positive sequences in the subset 1:  174
Total number positive sequences in the subset 2:  348

/var/folders/8v/dft5tkg533s0f0n7c3jl_mwr0000gn/T/ipykernel_2330/192778654.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset.loc[subset['EntryID'] == str(prot.id), 'Sequence'] = str(prot.seq)
/var/folders/8v/dft5tkg533s0f0n7c3jl_mwr0000gn/T/ipykernel_2330/192778654.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset.loc[subset['EntryID'] == str(prot.id), 'Set'] = f"{i}"

Total number positive sequences in the subset 3:  522
Total number positive sequences in the subset 4:  696
Total number positive sequences in the subset 5:  874
Total number negative sequences in the subset 1:  2303
Total number negative sequences in the subset 2:  3732
Total number negative sequences in the subset 3:  5161
Total number negative sequences in the subset 4:  6590
Total number negative sequences in the subset 5:  8021

In [18]:
len(subset)

8021

In [19]:
subset

,EntryID,OrganismName,Kingdom,SequenceLength,SPStart,SPEnd,Class,Sequence,Set,HelixDomain
0,P0C8G7,Pomacea canaliculata,Metazoa,286,1.0,30.0,Positive,MVKKIHFIMERHASIVAFLLAVLALTESQAFTSVKLPRDEHWPYNY...,1,NaN
1,P48816,Bombyx mori,Metazoa,137,1.0,18.0,Positive,MQKLIIFALVVLCVGSEAKTFTRCGLVHELRKHGFEENLMRNWVCL...,1,NaN
2,Q42502,Solanum tuberosum,Viridiplantae,386,1.0,23.0,Positive,MATTKSVLVLFFMILATTSSTCATLGEMVTVLSIDGGGIKGIIPAT...,1,NaN
3,P11590,Mus musculus,Metazoa,178,1.0,16.0,Positive,MKLLLCLGLTLVCIHAEEATSKGQNLNVEKINGEWFSILLASDKRE...,1,NaN
4,Q6DWK3,Colletotrichum lindemuthianum,Fungi,248,1.0,26.0,Positive,MHFSTLFGAAATAALAGSTNASPLARRQVPVGTPILQCTQPGLVAL...,1,NaN
...,...,...,...,...,...,...,...,...,...,...
8016,X5HYT8,Oryza sativa subsp. japonica,Viridiplantae,425,NaN,NaN,Negative,MASPGPAAGMQQKLEAAAAAAGGGDGAEWGRGMQKMEAVGAGGEGV...,5,False
8017,P97411,Mus musculus,Metazoa,478,NaN,NaN,Negative,MSGHKCYSWELQDRFAQDKSVVNKMQQKYWETKQAFIKATGKKEDE...,5,False
8018,Q9P305,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,131,NaN,NaN,Negative,MSEDLSPTSSRVDLSNPHGFTKEGVDLSKLSPQELKLYKMYGKLPS...,5,False
8019,P39995,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,279,NaN,NaN,Negative,MDKEVSELVVLQLIHTLISNKNEELVRNGGGINMIGNNLRISLVKL...,5,False
8020,B6VQ60,Caenorhabditis elegans,Metazoa,612,NaN,NaN,Negative,MADVALRITETVARLQKELKCGICCSTYKDPILSTCFHIFCRSCIN...,5,False

In [20]:
subset.loc[subset['Set'] == "5"]

,EntryID,OrganismName,Kingdom,SequenceLength,SPStart,SPEnd,Class,Sequence,Set,HelixDomain
696,O97939,Sus scrofa,Metazoa,1142,1.0,38.0,Positive,MLLSCRHGASSPKLDNLVPSGKMKILLVFLGLLCYSAAMPMQMPRM...,5,NaN
697,P30440,Felis catus,Metazoa,109,1.0,17.0,Positive,MRGALLVLALLVTQALGVKMAETCPIFYDVFFAVANGNELLLDLSL...,5,NaN
698,P43497,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,92,1.0,20.0,Positive,MQFSTVASVAFVALANFVAAESAAAISQITDGQIQATTTATTEATT...,5,NaN
699,O14786,Homo sapiens,Metazoa,923,1.0,21.0,Positive,MERGLPLLCAVLALVLAPAGAFRNDKCGDTIKIESPGYLTSPGYPH...,5,NaN
700,Q8NBJ9,Homo sapiens,Metazoa,832,1.0,18.0,Positive,MFALGLPFLVLLVASVESHLGVLGPKNVSQKDAEFERTYVDEVNSE...,5,NaN
...,...,...,...,...,...,...,...,...,...,...
8016,X5HYT8,Oryza sativa subsp. japonica,Viridiplantae,425,NaN,NaN,Negative,MASPGPAAGMQQKLEAAAAAAGGGDGAEWGRGMQKMEAVGAGGEGV...,5,False
8017,P97411,Mus musculus,Metazoa,478,NaN,NaN,Negative,MSGHKCYSWELQDRFAQDKSVVNKMQQKYWETKQAFIKATGKKEDE...,5,False
8018,Q9P305,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,131,NaN,NaN,Negative,MSEDLSPTSSRVDLSNPHGFTKEGVDLSKLSPQELKLYKMYGKLPS...,5,False
8019,P39995,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,279,NaN,NaN,Negative,MDKEVSELVVLQLIHTLISNKNEELVRNGGGINMIGNNLRISLVKL...,5,False
8020,B6VQ60,Caenorhabditis elegans,Metazoa,612,NaN,NaN,Negative,MADVALRITETVARLQKELKCGICCSTYKDPILSTCFHIFCRSCIN...,5,False

In [21]:
train_bench = pd.concat([benchmark , subset] , ignore_index=True)
train_bench.to_csv("train_bench.tsv",sep="\t", index=False)

In [22]:
print("Training Positives",len(subset.loc[subset['Class'] == "Positive"]))
print("Training Negatives",len(subset.loc[subset['Class'] == "Negative"]))
print("Benchmark Positives",len(benchmark.loc[benchmark['Class'] == "Positive"]))
print("Benchmark Positives",len(benchmark.loc[benchmark['Class'] == "Negative"]))

Training Positives 874
Training Negatives 7147
Benchmark Positives 219
Benchmark Positives 1787